version: "3.5"

networks:
  traefik:
    name: traefik
    driver: bridge
    attachable: true
    internal: false

services:
  traefik:
    container_name: traefik
    image: "traefik:latest"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api.insecure=true
      - --log.level=WARN
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Expose traefik dashboard at the address https://traefik.${DOMAIN}:80
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
    networks:
      - traefik

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Expose portainer dashboard at the address https://portainer.${DOMAIN}:80
      - "traefik.http.routers.frontend.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"

      # Expose edge agents at the address https://edge.${DOMAIN}:80
      - "traefik.http.routers.edge.rule=Host(`edge.${DOMAIN}`)"
      - "traefik.http.routers.edge.entrypoints=web"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
    networks:
      - traefik

volumes:
  portainer_data:
