version: "3.3"

services:
  traefik:
    container_name: traefik
    image: "traefik:latest"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=ERROR
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.email=${CERT_EMAIL}
      - --certificatesresolvers.leresolver.acme.storage=./certs/acme.json
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certificates/acme.json:/certs/acme.json"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # Expose traefik dashboard at the address https://traefik.${DOMAIN}
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=leresolver"

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # Expose portainer dashboard at the address https://portainer.${DOMAIN}
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=leresolver"

      # Expose edge agents at the address https://edge.${DOMAIN}
      - "traefik.http.routers.edge.rule=Host(`edge.${DOMAIN}`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=leresolver"

  host:
    container_name: host
    build: "./docker/test-host"
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./bin:/home/developer/bin:ro"
      - "./certificates:/home/developer/certificates"
      - "./traefik.d:/home/developer/traefik.d"
      - "./10-install-docker.sh:/home/developer/10-install-docker.sh:ro"
      - "./20-prepare-host.sh:/home/developer/20-prepare-host.sh:ro"
      - "./docker-compose.yml:/home/developer/docker-compose.yml"
      - "./.env-dist:/home/developer/.env-dist:ro"

volumes:
  portainer_data:
