version: "3.5"

services:
  joomla:
    container_name: joomla
    image: "joomla:latest"
    depends_on:
      - joomla-db
    environment:
      - JOOMLA_DB_HOST=mysql
      - JOOMLA_DB_NAME="${JOOMLA_DB_NAME}"
      - JOOMLA_DB_PASSWORD="${JOOMLA_DB_PASSWORD}"
    links:
      - "joomla-db:mysql"
    networks:
      - local
      - joomla
    labels:
      # Expose container at the address https://joomla.${DOMAIN}
      - "traefik.enable=true"
      - "traefik.http.routers.joomla.rule=Host(`joomla.${DOMAIN}`)"
      - "traefik.http.routers.joomla.entrypoints=web"
      - "traefik.http.routers.joomla.service=joomla"
      - "traefik.http.services.joomla.loadbalancer.server.port=80"

  joomla-db:
    container_name: joomla-db
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD="${JOOMLA_DB_PASSWORD}"
    ports:
      - "3306:3306"
    networks:
      - joomla

networks:
  local:
    external:
      name: local
  joomla:
    name: joomla
